# Generated by Django 3.2.5 on 2021-08-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('H', 'HIGH'), ('M', 'MEDIUM')], max_length=10)),
            ],
            options={
                'verbose_name': 'The Question',
                'verbose_name_plural': 'People Questions',
            },
        ),
    ]
